### ISSUE TITLE
agent模式无法播放youtube的视频

### ISSUE THREAD

**Issue by koolwiki** [coyove/goflyway#115]
如题，测试了一下agent模式，感觉挺好的。有个问题就是打开youtube网页后，随便点开一个视频都无法播放视频，一直处于转圈状态，网页上其他文字和图片都不受影响，只是没法播放视频。信息如下：

D:\goflyway>goflyway.exe -up=agent://testdomain.com:443 -lv dbg0
2018-10-23 18:43:09.126 CST,main.go:267, INFO ,goflyway 181021015134
2018-10-23 18:43:09.151 CST,main.go:270, WARNING ,Please change the default password: -k=<NEW PASSWORD>
2018-10-23 18:43:09.192 CST,main.go:280, DEBUG ,"ACL chinalist.txt: 0 black rules, 40925 white rules, 0 gray rules"
2018-10-23 18:43:09.193 CST,main.go:436, INFO ,Upstream config: agent://testdomain.com:443
2018-10-23 18:43:09.194 CST,main.go:475, WARNING ,"Agent is not safe, don't use it to access your important data"
2018-10-23 18:43:09.194 CST,main.go:416, INFO ,Client 72727e8 started: you->mitm->0.0.0.0:8100->testdomain.com:443(agent)
2018-10-23 18:43:09.194 CST,main.go:412, INFO ,Web console started at 127.0.0.1:8110
2018-10-23 18:43:19.769 CST,mitm.go:50, DEBUG ,Self signing: www.youtube.com
2018-10-23 18:43:19.786 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.youtube.com:443
2018-10-23 18:43:20.151 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.youtube.com:443
2018-10-23 18:43:20.192 CST,mitm.go:50, DEBUG ,Self signing: i.ytimg.com
2018-10-23 18:43:20.210 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i.ytimg.com:443
2018-10-23 18:43:20.741 CST,mitm.go:50, DEBUG ,Self signing: clients4.google.com
2018-10-23 18:43:20.773 CST,mitm.go:375, DEBUG ,Agent - POST ssl://clients4.google.com:443
2018-10-23 18:43:21.319 CST,mitm.go:336, ERROR ,"IO copy 0 bytes: write 127.0.0.1:3172, Software caused connection abort"
2018-10-23 18:43:21.545 CST,mitm.go:50, DEBUG ,Self signing: raw.githubusercontent.com
2018-10-23 18:43:21.564 CST,mitm.go:375, DEBUG ,Agent - GET ssl://raw.githubusercontent.com:443
2018-10-23 18:43:21.610 CST,mitm.go:375, DEBUG ,Agent - POST ssl://www.youtube.com:443
2018-10-23 18:43:22.079 CST,mitm.go:50, DEBUG ,Self signing: i1.ytimg.com
2018-10-23 18:43:22.114 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i1.ytimg.com:443
2018-10-23 18:43:22.256 CST,mitm.go:50, DEBUG ,Self signing: i9.ytimg.com
2018-10-23 18:43:22.300 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i9.ytimg.com:443
2018-10-23 18:43:22.547 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i.ytimg.com:443
2018-10-23 18:43:22.549 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i.ytimg.com:443
2018-10-23 18:43:22.550 CST,mitm.go:50, DEBUG ,Self signing: r1---sn-5uaeznyz.googlevideo.com
2018-10-23 18:43:22.569 CST,mitm.go:375, DEBUG ,Agent - GET ssl://r1---sn-5uaeznyz.googlevideo.com:443
2018-10-23 18:43:22.617 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.youtube.com:443
2018-10-23 18:43:22.631 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.youtube.com:443
2018-10-23 18:43:22.632 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.youtube.com:443
2018-10-23 18:43:22.638 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.youtube.com:443
2018-10-23 18:43:22.638 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.youtube.com:443
2018-10-23 18:43:22.800 CST,mitm.go:336, ERROR ,"IO copy 0 bytes: write 127.0.0.1:3187, Software caused connection abort"
2018-10-23 18:43:22.967 CST,mitm.go:336, ERROR ,"IO copy 0 bytes: write 127.0.0.1:3183, Software caused connection abort"
2018-10-23 18:43:23.085 CST,mitm.go:336, ERROR ,"IO copy 0 bytes: write 127.0.0.1:3182, Software caused connection abort"
2018-10-23 18:43:23.119 CST,mitm.go:50, DEBUG ,Self signing: yt3.ggpht.com
2018-10-23 18:43:23.292 CST,mitm.go:50, DEBUG ,Self signing: r1---sn-5uaeznkl.googlevideo.com
2018-10-23 18:43:23.325 CST,mitm.go:375, DEBUG ,Agent - GET ssl://r1---sn-5uaeznkl.googlevideo.com:443
2018-10-23 18:43:23.373 CST,mitm.go:336, ERROR ,"IO copy 0 bytes: write 127.0.0.1:3198, Software caused connection abort"
2018-10-23 18:43:23.405 CST,mitm.go:336, ERROR ,"IO copy 0 bytes: write 127.0.0.1:3197, Software caused connection abort"
2018-10-23 18:43:23.418 CST,mitm.go:336, ERROR ,"IO copy 0 bytes: write 127.0.0.1:3189, Software caused connection abort"
2018-10-23 18:43:23.468 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.youtube.com:443
2018-10-23 18:43:23.489 CST,mitm.go:375, DEBUG ,Agent - GET ssl://r1---sn-5uaeznkl.googlevideo.com:443
2018-10-23 18:43:23.600 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.youtube.com:443
2018-10-23 18:43:23.642 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.youtube.com:443
2018-10-23 18:43:23.672 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.youtube.com:443
2018-10-23 18:43:23.809 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.youtube.com:443
2018-10-23 18:43:25.630 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.youtube.com:443
2018-10-23 18:43:30.288 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.youtube.com:443
2018-10-23 18:43:30.291 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.youtube.com:443
2018-10-23 18:43:30.295 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.youtube.com:443
2018-10-23 18:43:30.295 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.youtube.com:443
2018-10-23 18:43:30.331 CST,mitm.go:375, DEBUG ,Agent - GET ssl://r1---sn-5uaeznkl.googlevideo.com:443
2018-10-23 18:43:30.334 CST,mitm.go:375, DEBUG ,Agent - GET ssl://r1---sn-5uaeznkl.googlevideo.com:443
2018-10-23 18:43:31.376 CST,mitm.go:375, DEBUG ,Agent - POST ssl://www.youtube.com:443
2018-10-23 18:43:31.409 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i1.ytimg.com:443
2018-10-23 18:43:31.437 CST,mitm.go:375, DEBUG ,Agent - GET ssl://yt3.ggpht.com:443
2018-10-23 18:43:31.443 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i.ytimg.com:443
2018-10-23 18:43:31.607 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i.ytimg.com:443
2018-10-23 18:43:31.608 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i.ytimg.com:443
2018-10-23 18:43:31.612 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i.ytimg.com:443
2018-10-23 18:43:31.612 CST,mitm.go:375, DEBUG ,Agent - GET ssl://yt3.ggpht.com:443
2018-10-23 18:43:31.730 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i.ytimg.com:443
2018-10-23 18:43:31.730 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i.ytimg.com:443
2018-10-23 18:43:32.098 CST,mitm.go:375, DEBUG ,Agent - POST ssl://www.youtube.com:443
2018-10-23 18:43:32.186 CST,mitm.go:375, DEBUG ,Agent - POST ssl://www.youtube.com:443
2018-10-23 18:43:32.313 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i.ytimg.com:443
2018-10-23 18:43:32.517 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i.ytimg.com:443
2018-10-23 18:43:32.578 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i.ytimg.com:443
2018-10-23 18:43:32.604 CST,mitm.go:50, DEBUG ,Self signing: www.google.com
2018-10-23 18:43:32.621 CST,mitm.go:375, DEBUG ,Agent - GET ssl://www.google.com:443
2018-10-23 18:43:32.728 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i.ytimg.com:443
2018-10-23 18:43:33.955 CST,mitm.go:50, DEBUG ,Self signing: s.ytimg.com
2018-10-23 18:43:33.991 CST,mitm.go:375, DEBUG ,Agent - GET ssl://s.ytimg.com:443
2018-10-23 18:43:34.061 CST,mitm.go:375, DEBUG ,Agent - GET ssl://s.ytimg.com:443
2018-10-23 18:43:35.980 CST,mitm.go:50, DEBUG ,Self signing: r1---sn-hp57kn6s.googlevideo.com
2018-10-23 18:43:36.006 CST,mitm.go:375, DEBUG ,Agent - GET ssl://r1---sn-hp57kn6s.googlevideo.com:443
2018-10-23 18:43:36.574 CST,mitm.go:375, DEBUG ,Agent - POST ssl://www.youtube.com:443
2018-10-23 18:43:37.466 CST,mitm.go:375, DEBUG ,Agent - GET ssl://r1---sn-hp57kn6s.googlevideo.com:443
2018-10-23 18:43:37.468 CST,mitm.go:375, DEBUG ,Agent - GET ssl://r1---sn-hp57kn6s.googlevideo.com:443
2018-10-23 18:43:39.668 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i9.ytimg.com:443
2018-10-23 18:43:41.877 CST,mitm.go:375, DEBUG ,Agent - POST ssl://www.youtube.com:443
2018-10-23 18:43:42.084 CST,mitm.go:375, DEBUG ,Agent - GET ssl://i9.ytimg.com:443
2018-10-23 18:43:42.553 CST,acl.go:42, ERROR ,ACL check error: DNS lookup failed: lookup r6---sn-25ge7nsl.googlevideo.com: getaddrinfow: A non-recoverable error occurred during a database lookup.
2018-10-23 18:43:42.818 CST,mitm.go:50, DEBUG ,Self signing: r6---sn-25ge7nsl.googlevideo.com
2018-10-23 18:43:42.835 CST,mitm.go:375, DEBUG ,Agent - GET ssl://r6---sn-25ge7nsl.googlevideo.com:443
2018-10-23 18:43:48.306 CST,mitm.go:375, DEBUG ,Agent - GET ssl://r1---sn-hp57kn6s.googlevideo.com:443
2018-10-23 18:43:48.307 CST,mitm.go:375, DEBUG ,Agent - GET ssl://r1---sn-5uaeznkl.googlevideo.com:443

**Comment by coyove** [comment]
这个bug应该是已经修掉过的，至少我这里油管正常。你可以打开一个视频，再打开开发者工具，观察一下XHR请求的结果是什么

**Comment by koolwiki** [comment]
显示Failed to load response data。

**Comment by coyove** [comment]
使用了2.0.0rc1的包依旧没有重现问题。
请尝试一下更换php hosting看看

**Comment by koolwiki** [comment]
我再看看吧，谢谢！
打开http://127.0.0.1:8110看代理规则发现有些googlevideo.com的域名无法解析出ip：
![image](https://user-images.githubusercontent.com/20160955/47358766-54a57680-d6fd-11e8-9ed6-452de1072d53.png)

**Comment by coyove** [comment]
控制台里面显示的全是`unknown`吗？即便是可以访问的网站也是unknown？

**Comment by koolwiki** [comment]
是的，能上的网站也是显示Unknonw，比如google。换了电脑也不行，另外000webhostapp.com同一个host下其他代理脚本可以看油管的视频。

**Comment by coyove** [comment]
我想到两点：
1. 通过最新的源码运行，观察是否出现同样情况
2. 通过wireshark或类似的软件抓**本地客户端**127.0.0.1:8100发出的包，其数据里面HTTP头的connection值应该总为close。之前修这个bug时，正是因为youtube返回的是keep-alive，才导致视频片段无法缓冲的问题。

**Comment by koolwiki** [comment]
1. 最新的源代码是指什么？我目前下载了release里面最新的RC版，自己也编译了一下，但都出现同样的问题。
2. 我后面测试一下再来反馈。

非常感谢！

**Comment by coyove** [comment]
如果是最新的代码，请观察一下web控制台里还是unknown吗，同时你可以把index.php的内容改为：
```
<?php
echo gethostbyname("googlevideo.com");
?>
```
然后访问它，看看能不能获得IP

**Comment by koolwiki** [comment]
1. 能够获取ip。
2. 加上代码后可以编译成功，但是使用-lv dbg0^dbg^info^log运行后自动退出（不使用可以正常运行并能够打开google等网站，但还是看不了油管视频），信息如下：
D:\goflyway>goflyway_windows_debug.exe -lv dbg0^dbg^info^log
panic: unexpected log level: dbg0dbginfolog

goroutine 1 [running]:
github.com/coyove/common/logg.(*Logger).SetLevel(0x10fd6210, 0x10fd4090, 0xe, 0x1)
        /home/xwfunny/work/src/github.com/coyove/common/logg/logg.go:71 +0x27a
github.com/coyove/common/logg.NewLogger(0x10fd4090, 0xe, 0x20)
        /home/xwfunny/work/src/github.com/coyove/common/logg/logg.go:110 +0x1b1
main.main()
        /home/xwfunny/work/src/github.com/coyove/goflyway/cmd/goflyway/main.go:255 +0xd1

![image](https://user-images.githubusercontent.com/20160955/47428755-d3b2b180-d7c6-11e8-9f37-e5aa2484c4c5.png)

**Comment by coyove** [comment]
-lv 后面的参数需要用双引号括起来

**Comment by coyove** [comment]
你用chrome的隐私窗口试一下，看看结果是什么

**Comment by coyove** [comment]
从dbg0输出的结果来看并不是host的问题，不过你可以给我测试一下：coyove@hotmail.com

**Comment by coyove** [comment]
今天更新了一下chrome，终于出现了同样的问题，正在排查中。
你可以试试http模式，看看能不能正常工作

**Comment by koolwiki** [comment]
http，https和cf模式一直都工作得很好。期待大佬早日找出bug！

ps：奇怪的是我用edge，ie等浏览器也会出现不能播放的问题。

**Comment by coyove** [comment]
是的，IE，firefox，safari都不行，应该是youtube返回了什么特殊的http头阻止了请求而不是浏览器的问题。
访问vimeo之类的视频网站是可以的。
