### ISSUE TITLE
【修改chinalist.txt后启动报错】panic: interface conversion: interface {} is int, not aclrouter.matchTree

### ISSUE THREAD

**Issue by hiboyhiboy** [coyove/goflyway#74]
```
#网站隐藏，ping得是104.24.101.14，已经成功cdn
cd $(dirname ` which goflyway`)
./goflyway -up="cf://*.*.com:80" -k="pass" -l="0.0.0.0:8100" -lv dbg
goflyway (build 180404210517)
* goflyway (build 180404210517)
* launched as client
panic: interface conversion: interface {} is int, not aclrouter.matchTree

goroutine 1 [running]:
github.com/coyove/goflyway/pkg/aclrouter.loadChinaList(0x9020000, 0x76887, 0x76a87, 0xd, 0x76a01, 0x0)
        /root/SS/go/src/github.com/coyove/goflyway/pkg/aclrouter/lookup.go:144 +0x418
github.com/coyove/goflyway/pkg/aclrouter.LoadACL(0x4117f5, 0xd, 0xd, 0x0, 0x0)
        /root/SS/go/src/github.com/coyove/goflyway/pkg/aclrouter/lookup.go:84 +0x424
main.main()
        /root/SS/goflyway/goflyway/cmd/goflyway/main.go:216 +0x314
```
经排查，是我使用自己补充的chinalist.txt导致启动失败
文件下载：[chinalist.txt](https://github.com/coyove/goflyway/files/1894432/chinalist.txt)

**Comment by coyove** [comment]
Fix in 4f8d5b3

**Comment by hiboyhiboy** [comment]
```
# * goflyway (build 180410200806)
* launched as client
panic: interface conversion: interface {} is int, not aclrouter.matchTree

goroutine 1 [running]:
github.com/coyove/goflyway/pkg/aclrouter.loadChinaList(0x920a000, 0x76887, 0x76a87, 0xd, 0x76a01, 0x0)
        /root/SS/go/src/github.com/coyove/goflyway/pkg/aclrouter/lookup.go:144 +0x418
github.com/coyove/goflyway/pkg/aclrouter.LoadACL(0x4117f5, 0xd, 0xd, 0x0, 0x0)
        /root/SS/go/src/github.com/coyove/goflyway/pkg/aclrouter/lookup.go:84 +0x424
main.main()
        /root/SS/goflyway/goflyway/cmd/goflyway/main.go:215 +0x268
```
刚刚试了 4f8d5b3 发现还是报错

**Comment by coyove** [comment]
`git checkout gdev`
